services:
  db:
    image: postgres:18
    container_name: dnd-companion-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ted
      POSTGRES_PASSWORD: dnd_password
      POSTGRES_DB: dnd_companion
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
